FROM maven:3-eclipse-temurin-17 AS build
WORKDIR /app
COPY . /app
RUN mvn clean package

FROM openjdk:17-alpine

COPY --from=build /app/target/ /home/app/StorageInterface/target

EXPOSE 9090
ENTRYPOINT [ "java", "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005", "-jar", "/home/app/StorageInterface/target/StorageInterface-0.0.1-SNAPSHOT.jar" ]