name: Update LocalWeb VM

on:
  push:
    branches:
      - dev
      - main

jobs:
    start-main:
        runs-on: ubuntu-latest
        env:
          DOCKER_HUB_TOKEN: ${{secrets.DOCKER_HUB_TOKEN}}
          DOCKER_HUB_USER: ${{secrets.DOCKER_HUB_USER}}
          RUN_NUMBER: ${{github.run_number}}
          REF_NAME: ${{github.ref_name}}

        steps:
            - name: Check out the repository
              uses: actions/checkout@v2
          
            - name: Set up Docker
              uses: docker/setup-buildx-action@v2

            - name: Login Dockerhub
              run: echo "${{env.DOCKER_HUB_TOKEN}}" | docker login -u ${{env.DOCKER_HUB_USER}} --password-stdin
      
            - name: Build image and push in dockerhub
              run: |
                  echo "env.RUN_NUMBER >>>>>>>>>>>>>>>>>>>>>> ${{github.run_number}}"
                  echo "env.REF_NAME >>>>>>>>>>>>>>>>>>>>>> ${{github.ref_name}}"
                  if [ ${{env.REF_NAME}} == "dev" ]; then
                    docker build --rm -f 'DockerFile' -t '${{env.DOCKER_HUB_USER}}/image-storageinterface-dev:latest' -t '${{env.DOCKER_HUB_USER}}/image-storageinterface-dev:${{env.RUN_NUMBER}}' '.'
                    docker push -a ${{env.DOCKER_HUB_USER}}/image-storageinterface-dev
                  elif [ ${{env.REF_NAME}} == "main" ]; then
                    docker build --rm -f 'DockerFile' -t '${{env.DOCKER_HUB_USER}}/image-storageinterface-prod:latest' -t '${{env.DOCKER_HUB_USER}}/image-storageinterface-prod:${{env.RUN_NUMBER}}' '.'
                    docker push -a ${{env.DOCKER_HUB_USER}}/image-storageinterface-prod
                  fi
                